version: '3'
volumes:
        crewing_mysql:
                external: true
networks:
  server-connection:
    driver: bridge
  db-connetion:
    driver: bridge

services:
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - server-connection
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - crewing-server
      - mysql-server
      - redis-server
  mysql-server:
    image: mysql:latest
    container_name: mysql-container
    volumes:
      - crewing_mysql:/var/lib/mysql
    networks:
      - db-connection
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: crewing
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Seoul
    env_file:
      - .env
    ports:
      - "3305:3306"
  redis-server:
    image: redis
    container_name: redis-server
    command: redis-server --port 6379
    hostname: redis
    ports:
      - "6378:6379"
    restart: always
  crewing-server:
    image: crewing-server
    container_name: crewing-server
    build: .
    ports:
      - "8081:8080"
    networks:
      - db-connection
      - server-connection
    env_file:
      - .env
    depends_on:
      - mysql-server
      - redis-server
