version: '3'
services:
  mysql-server:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: crewing
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    ports:
      - "3305:3306"
  redis-server:
    image: redis
    command: redis-server --port 6379
    hostname: redis
    ports:
      - "6379:6379"
    restart: always
  crewing-server:
    image: crewing-server
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-server:3306/crewing?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - mysql-server
      - redis-server
